version: "3.8"
services:
  db:
    image: postgres:13
    volumes:
      - kurisudb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    networks:
      kurisu-net:
        aliases:
          - kurisu_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kurisu"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - db_user
      - db_password
    restart: always

  kurisu:
    image: ghcr.io/nh-server/kurisu
    environment:
      KURISU_TOKEN_FILE: /run/secrets/kurisu_token
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
      SERVER_LOGS_URL_FILE: /run/secrets/server_logs_url
    networks:
      - kurisu-net
      - panopticon-net
    secrets:
      - kurisu_token
      - db_user
      - db_password
      - server_logs_url
    depends_on:
      db:
        condition: service_healthy
    restart: always

networks:
  kurisu-net:
    name: kurisu
    driver: bridge
  panopticon-net:
    name: panopticon
    external: true

volumes:
  kurisudb:

secrets:
  db_user:
    file: /opt/secrets/kurisu/db_user
  db_password:
    file: /opt/secrets/kurisu/db_password
  kurisu_token:
    file: /opt/secrets/kurisu/token
  server_logs_url:
    file: /opt/secrets/kurisu/server_logs_url
